[package]
name = "barbacane"
description = "Barbacane data plane â€” spec-driven API gateway"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
barbacane-router = { workspace = true }
tokio = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
http-body-util = { workspace = true }
http = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true }
flate2 = { workspace = true }
tar = { workspace = true }
thiserror = { workspace = true }
